version: '3'
services:
  homeseer:
    image: worthington
    ports:
    - "80:80"
  gpio:
    image: gpio
    privileged: true
    command: sh -c '/usr/src/app/wait-for -t 60 homeseer:80 -- python -u /usr/src/app/poll_gpio.py'
    depends_on:
      - homeseer
